/**
 * The Malooch API
 * Auto genertaed Malooch API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

    // CommonJS-like environments that support module.exports, like Node.
    const ApiClient = require('../ApiClient')
    , RoutesExchangeReportResponseData = require('./RoutesExchangeReportResponseData')





  /**
   * The RoutesExchangeReportResponse model module.
   * @module model/RoutesExchangeReportResponse
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>RoutesExchangeReportResponse</code>.
   * @alias module:model/RoutesExchangeReportResponse
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>RoutesExchangeReportResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RoutesExchangeReportResponse} obj Optional instance to populate.
   * @return {module:model/RoutesExchangeReportResponse} The populated <code>RoutesExchangeReportResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('count')) {
        obj['count'] = ApiClient.convertToType(data['count'], 'Integer');
      }
      if (data.hasOwnProperty('data')) {
        obj['data'] = ApiClient.convertToType(data['data'], [RoutesExchangeReportResponseData]);
      }
    }
    return obj;
  }

  /**
   * @member {Integer} count
   */
  exports.prototype['count'] = undefined;
  /**
   * @member {Array.<module:model/RoutesExchangeReportResponseData>} data
   */
  exports.prototype['data'] = undefined;



  module.exports = exports;



