/**
 * The Malooch API
 * Auto genertaed Malooch API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

    // CommonJS-like environments that support module.exports, like Node.
    const ApiClient = require('../ApiClient')
    





  /**
   * The RoutesResponseLoginOK model module.
   * @module model/RoutesResponseLoginOK
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>RoutesResponseLoginOK</code>.
   * @alias module:model/RoutesResponseLoginOK
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>RoutesResponseLoginOK</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RoutesResponseLoginOK} obj Optional instance to populate.
   * @return {module:model/RoutesResponseLoginOK} The populated <code>RoutesResponseLoginOK</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('email')) {
        obj['email'] = ApiClient.convertToType(data['email'], 'String');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Integer');
      }
      if (data.hasOwnProperty('token')) {
        obj['token'] = ApiClient.convertToType(data['token'], 'String');
      }
      if (data.hasOwnProperty('user_type')) {
        obj['user_type'] = ApiClient.convertToType(data['user_type'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} email
   */
  exports.prototype['email'] = undefined;
  /**
   * @member {Integer} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} token
   */
  exports.prototype['token'] = undefined;
  /**
   * @member {String} user_type
   */
  exports.prototype['user_type'] = undefined;



  module.exports = exports;



