/**
 * The Malooch API
 * Auto genertaed Malooch API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

    // CommonJS-like environments that support module.exports, like Node.
    const ApiClient = require('../ApiClient')
    





  /**
   * The RoutesRegistrationPayload model module.
   * @module model/RoutesRegistrationPayload
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>RoutesRegistrationPayload</code>.
   * @alias module:model/RoutesRegistrationPayload
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>RoutesRegistrationPayload</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RoutesRegistrationPayload} obj Optional instance to populate.
   * @return {module:model/RoutesRegistrationPayload} The populated <code>RoutesRegistrationPayload</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('email')) {
        obj['email'] = ApiClient.convertToType(data['email'], 'String');
      }
      if (data.hasOwnProperty('password')) {
        obj['password'] = ApiClient.convertToType(data['password'], 'String');
      }
      if (data.hasOwnProperty('user_type')) {
        obj['user_type'] = ApiClient.convertToType(data['user_type'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} email
   */
  exports.prototype['email'] = undefined;
  /**
   * @member {String} password
   */
  exports.prototype['password'] = undefined;
  /**
   * @member {String} user_type
   */
  exports.prototype['user_type'] = undefined;



  module.exports = exports;



